server:
  port: 8080

spring:
  application:
    name: ringring
  devtools:
    restart.enabled: false    # auto restart off
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ENC(2+J4J5Ajueeyxvm805PaPpR9phL8keZqhbnZdczsqB0CAmhoGbMtVJD2B7ULhoEPF+EpIYXSXdE=)
    username: ENC(4Pke5ls4JZL/kkBhpbT0SIXIb8rdj9IP)
    password: ENC(uNmIkFM053QBuZBVIllMzXA2oNG2w0eI)
  jpa:
    hibernate:
      ddl-auto: none
  data:
    redis:
      host: ENC(MCvT0HQ67m4BjwY9LcN0pcjs1xqFTgp9)
      port: 6379
      password: ENC(r2uc6/WC014u/faSjNdc6JZE+jNm0VcF)
  servlet:
    multipart:
      max-file-size: 5MB      # Maximum size allowed for uploaded files
      max-request-size: 10MB  # Maximum size allowed for multipart/form-data requests (includes all files + form fields)
      enabled: true           # Enable multipart uploads (default is true)
  mail:
    host: smtp.gmail.com
    port: 587
    username: ENC(SWe+iecUIao1gfeCI5PPL/9RnC/vJGFvg9GFE4V81S+7nGqRKzezAw==)
    password: ENC(0dn1GMoRT56mP/3Dzwh14YI882Jd767oru7I1wJ/yBs=)
    properties:
      mail.smtp.auth: true
      mail.smtp.starttls.enable: true
      mail.smtp.starttls.required: true
    protocol: smtp
    default-encoding: UTF-8

security:
  jwt:
    secret-key: ${RINGRING_JWT_SECRET_KEY}
    access-token-expire: 86400000                   # 개발 편의성을 위해서 Access Token 유효시간을 24시간으로 설정 / 300000
    refresh-token-expire: 86400000
    cookie-config:
      name: refresh_token
      path: /api/v1/auth/token/reissue
  cors:
    allowed-origins: http://localhost:3000

jasypt:
  encryptor:
    key: ${RINGRING_JASYPT_ENCRYPTOR_KEY}

logging:
  level:
    root: error
    com.sideforge.ringring: debug