-- tb_account
CREATE TABLE tb_account (
    id bpchar(32) NOT NULL,
    email varchar(100) NULL,
    "password" varchar(255) NULL,
    is_social bool NOT NULL,
    social_provider varchar(255) NULL,
    provider_id varchar(255) NULL,
    "name" varchar(50) NOT NULL,
    nickname varchar(50) NOT NULL,
    phone_number varchar(20) NOT NULL,
    created_at timestamp(6) NOT NULL,
    updated_at timestamp(6) NOT NULL,
    status varchar(255) NOT NULL,
    failed_login_count int4 NULL,
    last_login_at timestamp(6) NULL,
    is_locked_at timestamp(6) NULL,
    CONSTRAINT tb_account_email_key UNIQUE (email),
    CONSTRAINT tb_account_pkey PRIMARY KEY (id),
    CONSTRAINT tb_account_social_provider_check CHECK (((social_provider)::text = ANY ((ARRAY['GOOGLE'::character varying, 'NAVER'::character varying])::text[]))),
    CONSTRAINT tb_account_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'INACTIVE'::character varying, 'LOCKED'::character varying, 'BANNED'::character varying, 'WITHDRAWN'::character varying])::text[])))
);
CREATE INDEX idx_user_email ON tb_account USING btree (email);

-- tb_account_role
CREATE TABLE tb_account_role (
    id bpchar(5) NOT NULL,
    "name" varchar(20) NOT NULL,
    CONSTRAINT tb_account_role_pkey PRIMARY KEY (id)
);

-- tb_account_role_mapping
CREATE TABLE tb_account_role_mapping (
    account_id varchar(255) NOT NULL,
    role_id varchar(255) NOT NULL,
    CONSTRAINT tb_account_role_mapping_pkey PRIMARY KEY (account_id, role_id)
);
ALTER TABLE tb_account_role_mapping ADD CONSTRAINT fkdnspwo3da6hm54mfukswr6px1 FOREIGN KEY (account_id) REFERENCES tb_account(id);
ALTER TABLE tb_account_role_mapping ADD CONSTRAINT fk33wtlbsd0oaprm493pn5n02sh FOREIGN KEY (role_id) REFERENCES tb_account_role(id);

-- tb_account_ban_history
CREATE TABLE tb_account_ban_history (
    id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    banned_id bpchar(32) NOT NULL,
    admin_id bpchar(32) NULL,
    "type" varchar(255) NOT NULL,
    reason varchar(255) NOT NULL,
    started_at timestamp(6) NOT NULL,
    ends_at timestamp(6) NULL,
    CONSTRAINT tb_account_ban_history_pkey PRIMARY KEY (id),
    CONSTRAINT tb_account_ban_history_type_check CHECK (((type)::text = ANY ((ARRAY['CAUTION_BAN'::character varying, 'TEMPORARY_BAN'::character varying, 'PERMANENT_BAN'::character varying])::text[])))
);
ALTER TABLE tb_account_ban_history ADD CONSTRAINT fkjl7497ia5owo426hsqf0wyswi FOREIGN KEY (admin_id) REFERENCES tb_account(id);
ALTER TABLE tb_account_ban_history ADD CONSTRAINT fkt4y8po87kl080jikv55en5c3r FOREIGN KEY (banned_id) REFERENCES tb_account(id);

-- tb_post
CREATE TABLE public.tb_post (
    id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    author_id bpchar(32) NOT NULL,
    "type" varchar(255) NOT NULL,
    title varchar(255) NOT NULL,
    created_at timestamp(6) NOT NULL,
    updated_at timestamp(6) NOT NULL,
    is_active bool NOT NULL,
    CONSTRAINT tb_post_pkey PRIMARY KEY (id),
    CONSTRAINT tb_post_type_check CHECK (((type)::text = 'REPORT'::text))
);

-- tb_post_content
CREATE TABLE public.tb_post_content (
    id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    post_id int8 NOT NULL,
    "content" text NOT NULL,
    CONSTRAINT tb_post_content_pkey PRIMARY KEY (id)
);
ALTER TABLE public.tb_post_content ADD CONSTRAINT fkmgjtome4irdck1m32cdh7utrm FOREIGN KEY (post_id) REFERENCES public.tb_post(id);

-- tb_post_attachment
CREATE TABLE public.tb_post_attachment (
    id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    post_id int8 NOT NULL,
    "type" varchar(255) NOT NULL,
    "name" varchar(50) NOT NULL,
    url varchar(255) NOT NULL,
    CONSTRAINT tb_post_attachment_pkey PRIMARY KEY (id),
    CONSTRAINT tb_post_attachment_type_check CHECK (((type)::text = ANY ((ARRAY['IMAGE'::character varying, 'AUDIO'::character varying, 'VIDEO'::character varying])::text[])))
);
ALTER TABLE public.tb_post_attachment ADD CONSTRAINT fkfhhtcoefk6l50e9138kgeth2a FOREIGN KEY (post_id) REFERENCES public.tb_post(id);