-- =====================================================================================================================
-- tb_account
-- =====================================================================================================================
CREATE TABLE public.tb_account (
    id bpchar(32) NOT NULL,
    email varchar(100) NULL,
    "password" varchar(255) NULL,
    is_social bool NOT NULL,
    social_provider varchar(255) NULL,
    provider_id varchar(255) NULL,
    "name" varchar(50) NOT NULL,
    nickname varchar(50) NOT NULL,
    phone_number varchar(20) NOT NULL,
    created_at timestamp(6) NOT NULL,
    updated_at timestamp(6) NOT NULL,
    status varchar(255) NOT NULL,
    failed_login_count int4 NULL,
    last_login_at timestamp(6) NULL,
    is_locked_at timestamp(6) NULL,
    CONSTRAINT tb_account_email_key UNIQUE (email),
    CONSTRAINT tb_account_pkey PRIMARY KEY (id),
    CONSTRAINT tb_account_social_provider_check CHECK (((social_provider)::text = ANY ((ARRAY['GOOGLE'::character varying, 'NAVER'::character varying])::text[]))),
    CONSTRAINT tb_account_status_check CHECK (((status)::text = ANY ((ARRAY['ACTIVE'::character varying, 'INACTIVE'::character varying, 'LOCKED'::character varying, 'BANNED'::character varying, 'WITHDRAWN'::character varying])::text[])))
);
CREATE INDEX idx_user_email ON public.tb_account USING btree (email);

-- =====================================================================================================================
-- tb_account_role
-- =====================================================================================================================
CREATE TABLE public.tb_account_role (
    id bpchar(5) NOT NULL,
    "name" varchar(20) NOT NULL,
    CONSTRAINT tb_account_role_pkey PRIMARY KEY (id)
);

-- =====================================================================================================================
-- tb_account_role_mapping
-- =====================================================================================================================
CREATE TABLE public.tb_account_role_mapping (
    account_id varchar(255) NOT NULL,
    role_id varchar(255) NOT NULL,
    CONSTRAINT tb_account_role_mapping_pkey PRIMARY KEY (account_id, role_id)
);
ALTER TABLE public.tb_account_role_mapping ADD CONSTRAINT fkdnspwo3da6hm54mfukswr6px1 FOREIGN KEY (account_id) REFERENCES public.tb_account(id);
ALTER TABLE public.tb_account_role_mapping ADD CONSTRAINT fk33wtlbsd0oaprm493pn5n02sh FOREIGN KEY (role_id) REFERENCES public.tb_account_role(id);

-- =====================================================================================================================
-- tb_account_ban_history
-- =====================================================================================================================
CREATE TABLE public.tb_account_ban_history (
    id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    banned_id bpchar(32) NULL,
    admin_id bpchar(32) NULL,
    "type" varchar(255) NOT NULL,
    reason varchar(255) NOT NULL,
    started_at timestamp(6) NOT NULL,
    ends_at timestamp(6) NULL,
    created_at timestamp(6) NOT NULL,
    CONSTRAINT tb_account_ban_history_pkey PRIMARY KEY (id),
    CONSTRAINT tb_account_ban_history_type_check CHECK (((type)::text = ANY ((ARRAY['CAUTION'::character varying, 'TEMPORARY'::character varying, 'PERMANENT'::character varying])::text[])))
);
ALTER TABLE public.tb_account_ban_history ADD CONSTRAINT fk67dmqlos5h1rirpily8hbql6a FOREIGN KEY (admin_id) REFERENCES public.tb_account(id);
ALTER TABLE public.tb_account_ban_history ADD CONSTRAINT fk9udblmkvw2pgkc4oil2p0fobu FOREIGN KEY (banned_id) REFERENCES public.tb_account(id);

-- =====================================================================================================================
-- tb_common_group_code
-- =====================================================================================================================
CREATE TABLE public.tb_common_group_code (
     group_code varchar(100) NOT NULL,
     group_name varchar(100) NOT NULL,
     description varchar(255) NULL,
     created_at timestamp(6) NOT NULL,
     updated_at timestamp(6) NOT NULL,
     is_active bool NOT NULL,
     CONSTRAINT tb_common_group_code_pkey PRIMARY KEY (group_code)
);

-- =====================================================================================================================
-- tb_common_code
-- =====================================================================================================================
CREATE TABLE public.tb_common_code (
    id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    group_code varchar(100) NOT NULL,
    code varchar(100) NOT NULL,
    code_name varchar(100) NOT NULL,
    description varchar(255) NULL,
    sort_order int4 NOT NULL,
    created_at timestamp(6) NOT NULL,
    updated_at timestamp(6) NOT NULL,
    is_active bool NOT NULL,
    CONSTRAINT tb_common_code_pkey PRIMARY KEY (id),
    CONSTRAINT uq_common_code_group_code_code UNIQUE (group_code, code)
);
ALTER TABLE public.tb_common_code ADD CONSTRAINT fk6s4mhmp9k3xkafghjo7n140xq FOREIGN KEY (group_code) REFERENCES public.tb_common_group_code(group_code);

-- =====================================================================================================================
-- tb_attachment
-- =====================================================================================================================
CREATE TABLE public.tb_attachment (
    id bpchar(32) NOT NULL,
    "name" varchar(255) NOT NULL,
    "type" varchar(255) NOT NULL,
    mime_type varchar(100) NOT NULL,
    url text NOT NULL,
    created_at timestamp(6) NOT NULL,
    CONSTRAINT tb_attachment_pkey PRIMARY KEY (id),
    CONSTRAINT tb_attachment_type_check CHECK (((type)::text = ANY ((ARRAY['IMAGE'::character varying, 'VIDEO'::character varying, 'AUDIO'::character varying, 'DOC'::character varying, 'ARCHIVE'::character varying, 'OTHER'::character varying])::text[])))
);

-- =====================================================================================================================
-- tb_board
-- =====================================================================================================================
CREATE TABLE public.tb_board (
     id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
     "name" varchar(50) NOT NULL,
     "type" varchar(255) NOT NULL,
     read_min_role bpchar(5) NOT NULL,
     write_min_role bpchar(5) NOT NULL,
     created_at timestamp(6) NOT NULL,
     updated_at timestamp(6) NOT NULL,
     CONSTRAINT tb_board_pkey PRIMARY KEY (id),
     CONSTRAINT tb_board_type_check CHECK (((type)::text = 'NOTICE'::text))
);

-- =====================================================================================================================
-- tb_post
-- =====================================================================================================================
CREATE TABLE public.tb_post (
    id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    board_id int8 NULL,
    author_id bpchar(32) NULL,
    "type" varchar(255) NOT NULL,
    title varchar(255) NOT NULL,
    content_version int4 NOT NULL,
    created_at timestamp(6) NOT NULL,
    updated_at timestamp(6) NOT NULL,
    is_active bool NOT NULL,
    view_count int4 NOT NULL,
    CONSTRAINT tb_post_pkey PRIMARY KEY (id),
    CONSTRAINT tb_post_type_check CHECK (((type)::text = 'REPORT'::text))
);
ALTER TABLE public.tb_post ADD CONSTRAINT fk87r3ehfqae0cbeqmconk3plxy FOREIGN KEY (author_id) REFERENCES public.tb_account(id);
ALTER TABLE public.tb_post ADD CONSTRAINT fksn6tvkjtynqrfxsooaojns5uu FOREIGN KEY (board_id) REFERENCES public.tb_board(id);

-- =====================================================================================================================
-- tb_post_content
-- =====================================================================================================================
CREATE TABLE public.tb_post_content (
    id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    post_id int8 NOT NULL,
    "content" text NOT NULL,
    version_no int4 NOT NULL,
    created_at timestamp(6) NOT NULL,
    CONSTRAINT tb_post_content_pkey PRIMARY KEY (id),
    CONSTRAINT ux_post_id_version_no UNIQUE (post_id, version_no)
);
ALTER TABLE public.tb_post_content ADD CONSTRAINT fkmgjtome4irdck1m32cdh7utrm FOREIGN KEY (post_id) REFERENCES public.tb_post(id);

-- =====================================================================================================================
-- tb_post_attachment_mapping
-- =====================================================================================================================
CREATE TABLE public.tb_post_attachment_mapping (
    post_id int8 NOT NULL,
    attachment_id varchar(255) NOT NULL,
    "usage" varchar(255) NOT NULL,
    CONSTRAINT tb_post_attachment_mapping_pkey PRIMARY KEY (post_id, attachment_id),
    CONSTRAINT tb_post_attachment_mapping_usage_check CHECK (((usage)::text = ANY ((ARRAY['FILE'::character varying, 'CONTENT'::character varying, 'THUMBNAIL'::character varying])::text[])))
);
ALTER TABLE public.tb_post_attachment_mapping ADD CONSTRAINT fkdgxnu7n4rctj5g0s3lebxfpis FOREIGN KEY (post_id) REFERENCES public.tb_post(id);
ALTER TABLE public.tb_post_attachment_mapping ADD CONSTRAINT fke0mlpgxpt8vwvwarsmqdc9dk FOREIGN KEY (attachment_id) REFERENCES public.tb_attachment(id);

-- =====================================================================================================================
-- tb_post_notice
-- =====================================================================================================================
CREATE TABLE public.tb_post_notice (
    post_id int8 NOT NULL,
    pinned bool NOT NULL,
    pinned_until timestamp(6) NULL,
    CONSTRAINT tb_post_notice_pkey PRIMARY KEY (post_id)
);
ALTER TABLE public.tb_post_notice ADD CONSTRAINT fkk0gj5bf3e1w79u505fjt4dc96 FOREIGN KEY (post_id) REFERENCES public.tb_post(id);

-- =====================================================================================================================
-- tb_report
-- =====================================================================================================================
CREATE TABLE public.tb_report (
    id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    phone_number varchar(20) NOT NULL,
    "type" varchar(255) NOT NULL,
    reported_by bpchar(32) NOT NULL,
    weight numeric(5, 2) NOT NULL,
    review_via varchar(255) NOT NULL,
    reviewed_by bpchar(32) NULL,
    status varchar(255) NOT NULL,
    created_at timestamp(6) NOT NULL,
    updated_at timestamp(6) NOT NULL,
    view_count int4 NOT NULL,
    CONSTRAINT tb_report_pkey PRIMARY KEY (id),
    CONSTRAINT tb_report_review_via_check CHECK (((review_via)::text = ANY ((ARRAY['PENDING'::character varying, 'AUTO'::character varying, 'MANUAL'::character varying])::text[]))),
    CONSTRAINT tb_report_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'SPAM'::character varying, 'RELEASED'::character varying])::text[]))),
    CONSTRAINT tb_report_type_check CHECK (((type)::text = ANY ((ARRAY['LOAN'::character varying, 'TELEMARKETING'::character varying, 'GAMBLING'::character varying, 'ADULT'::character varying, 'INSURANCE'::character varying, 'SURVEY'::character varying, 'INVESTMENT'::character varying, 'IMPERSONATION'::character varying, 'ETC'::character varying])::text[]))),
    CONSTRAINT uk_phone_number_type UNIQUE (phone_number, type)
);
CREATE INDEX idx_phone_number_type ON public.tb_report USING btree (phone_number, type);
ALTER TABLE public.tb_report ADD CONSTRAINT fk1y4tjheld6b5lcvvacyyokt10 FOREIGN KEY (reviewed_by) REFERENCES public.tb_account(id);
ALTER TABLE public.tb_report ADD CONSTRAINT fk9ht93ln3ppe6xea9vodafamye FOREIGN KEY (reported_by) REFERENCES public.tb_account(id);

-- =====================================================================================================================
-- tb_report_attachment_mapping
-- =====================================================================================================================
CREATE TABLE public.tb_report_attachment_mapping (
    report_id int8 NOT NULL,
    attachment_id varchar(255) NOT NULL,
    CONSTRAINT tb_report_attachment_mapping_pkey PRIMARY KEY (report_id, attachment_id)
);
ALTER TABLE public.tb_report_attachment_mapping ADD CONSTRAINT fk9y242cbo1obpt11f07sy9926m FOREIGN KEY (report_id) REFERENCES public.tb_report(id);
ALTER TABLE public.tb_report_attachment_mapping ADD CONSTRAINT fkl2cos9dlci51f5r03603qu119 FOREIGN KEY (attachment_id) REFERENCES public.tb_attachment(id);

-- =====================================================================================================================
-- tb_report_history
-- =====================================================================================================================
CREATE TABLE public.tb_report_history (
    id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    report_id int8 NOT NULL,
    from_status varchar(255) NULL,
    to_status varchar(255) NOT NULL,
    reason varchar(255) NULL,
    created_by bpchar(32) NULL,
    created_at timestamp(6) NOT NULL,
    CONSTRAINT tb_report_history_from_status_check CHECK (((from_status)::text = ANY ((ARRAY['PENDING'::character varying, 'SPAM'::character varying, 'RELEASED'::character varying])::text[]))),
    CONSTRAINT tb_report_history_pkey PRIMARY KEY (id),
    CONSTRAINT tb_report_history_to_status_check CHECK (((to_status)::text = ANY ((ARRAY['PENDING'::character varying, 'SPAM'::character varying, 'RELEASED'::character varying])::text[])))
);
ALTER TABLE public.tb_report_history ADD CONSTRAINT fkd0mwbj4tihy3bljbs5g2pxwp1 FOREIGN KEY (report_id) REFERENCES public.tb_report(id);

-- =====================================================================================================================
-- tb_report_notification
-- =====================================================================================================================
CREATE TABLE public.tb_report_notification (
    id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    report_id int8 NOT NULL,
    account_id bpchar(32) NOT NULL,
    spam_detected bool NOT NULL,
    not_spam_detected bool NOT NULL,
    created_at timestamp(6) NOT NULL,
    CONSTRAINT tb_report_notification_pkey PRIMARY KEY (id)
);
ALTER TABLE public.tb_report_notification ADD CONSTRAINT fkhy4w8ebp7wskdpx16y5xoemhe FOREIGN KEY (account_id) REFERENCES public.tb_account(id);
ALTER TABLE public.tb_report_notification ADD CONSTRAINT fkilp2mt32al14rcqa5xahxsm5a FOREIGN KEY (report_id) REFERENCES public.tb_report(id);

-- =====================================================================================================================
-- tb_report_vote
-- =====================================================================================================================
CREATE TABLE public.tb_report_vote (
    id int8 GENERATED BY DEFAULT AS IDENTITY( INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1 CACHE 1 NO CYCLE) NOT NULL,
    report_id int8 NOT NULL,
    account_id bpchar(32) NOT NULL,
    spam_type varchar(255) NULL,
    is_spam bool NOT NULL,
    created_at timestamp(6) NOT NULL,
    updated_at timestamp(6) NOT NULL,
    CONSTRAINT tb_report_vote_pkey PRIMARY KEY (id),
    CONSTRAINT tb_report_vote_spam_type_check CHECK (((spam_type)::text = ANY ((ARRAY['LOAN'::character varying, 'TELEMARKETING'::character varying, 'GAMBLING'::character varying, 'ADULT'::character varying, 'INSURANCE'::character varying, 'SURVEY'::character varying, 'INVESTMENT'::character varying, 'IMPERSONATION'::character varying, 'ETC'::character varying])::text[])))
);
ALTER TABLE public.tb_report_vote ADD CONSTRAINT fk2s27rggjnd9pjn4i2tw6hcapv FOREIGN KEY (report_id) REFERENCES public.tb_report(id);
ALTER TABLE public.tb_report_vote ADD CONSTRAINT fk7nqasaudneg7cvf0i9k5lkd7s FOREIGN KEY (account_id) REFERENCES public.tb_account(id);